プログラム (program) ::= "program" "名前" ";" ブロック "."

ブロック (block) ::= { 変数宣言部 | 副プログラム宣言 } 複合文

変数宣言部 (variable declaration) ::= 
    "var" 変数名の並び ":" 型 ";" { 変数名の並び ":" 型 ";" }

変数名の並び (variable names) ::= "名前" { "," "名前" }

型 (type) ::= ("integer" | "boolean" | "char")
            | "array" "[" "符号なし整数" "]" "of" ("integer" | "boolean" | "char")

副プログラム宣言 (subprogram declaration) ::= 
    "procedure" "名前" [ 仮引数部 ] ";" [ 変数宣言部 ] 複合文 ";"

仮引数部 (formal parameters) ::= 
    "(" 変数名の並び ":" 型 { ";" 変数名の並び ":" 型 } ")"

複合文 (compound statement) ::= "begin" 文 { ";" 文 } "end"

文 (statement) ::= 
      変数 ":=" 式                                                      /* 代入文 */
    | "if" 式 "then" 文 [ "else" 文 ]                                   /* 分岐文 */
    | "while" 式 "do" 文                                                /* 繰り返し文 */
    | "break"                                                           /* 脱出文 */
    | "call" "名前" [ "(" 式の並び ")" ]                                 /* 手続き呼び出し文 */
    | "return"                                                          /* 戻り文 */
    | ("read" | "readln") [ "(" 変数 { "," 変数 } ")" ]                 /* 入力文 */
    | ("write" | "writeln") [ "(" 出力指定 { "," 出力指定 } ")" ]       /* 出力文 */
    | 複合文
    | ε                                                                 /* 空文 */

式の並び (expressions) ::= 式 { "," 式 }

変数 (variable) ::= "名前" [ "[" 式 "]" ]

式 (expression) ::= 単純式 { ("=" | "<>" | "<" | "<=" | ">" | ">=") 単純式 }
    /* 関係演算子は左に結合的である */

単純式 (simple expression) ::= [ "+" | "-" ] 項 { ("+" | "-" | "or") 項 }
    /* 加法演算子は左に結合的である */

項 (term) ::= 因子 { ("*" | "div" | "and") 因子 }
    /* 乗法演算子は左に結合的である */

因子 (factor) ::= 
      変数 
    | "符号なし整数" | "false" | "true" | "文字列"     /* 定数 */
    | "(" 式 ")" 
    | "not" 因子 
    | ("integer" | "boolean" | "char") "(" 式 ")"     /* 標準型キャスト */

出力指定 (output format) ::= 式 [ ":" "符号なし整数" ] | "文字列"
    /* この"文字列"の長さ(文字数)は1以外である．
       長さが1の場合は式から生成される定数の一つである"文字列"とする */